name: release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: build release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: get release version
        id: release-version
        run: |
          echo "$GITHUB_REF_NAME" | sed 's|^[a-zA-Z]\+|RELEASE_VERSION=|' >> $GITHUB_OUTPUT

      # create asset
      - name: create tar archive
        run: |
          cd .. &&
          cp -rp ${{ github.event.repository.name }} ${{ github.event.repository.name }}-${{ steps.release-version.outputs.RELEASE_VERSION }} &&
          tar \
            --create \
            --gzip \
            --verbose \
            --exclude='.gitignore' \
            --exclude='.github' \
            --exclude='.git' \
            --file=${{ github.event.repository.name }}-${{ steps.release-version.outputs.RELEASE_VERSION }}.tar.gz \
            ${{ github.event.repository.name }}-${{ steps.release-version.outputs.RELEASE_VERSION }}

      - name: debug
        run: |
          ls -al ./
          ls -al ../

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: false
          draft: false
          files: |
            ./../${{ github.event.repository.name }}-${{ steps.release-version.outputs.RELEASE_VERSION }}.tar.gz
